name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLProject/train_data.csv"  
  TARGET_VAR: "Weather Type"           

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository ke $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Instal Miniconda dan setup environment
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          miniconda-version: "latest"

      - name: Create Conda environment
        run: conda env create -f MLProject/conda.yaml

      - name: Run MLflow project
        run: conda run -n mlflow-env mlflow run ./MLProject --env-manager=conda

      # Dapatkan run_id terbaru dari MLflow
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"
          
      # Bangun Docker Image untuk model
      - name: Build Docker Image
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "weather-model" 

      # Login ke Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag weather-model ${{ secrets.DOCKER_HUB_USERNAME }}/weather-model:latest

      # Push Docker Image ke Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/weather-model:latest
