name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLProject/train_data.csv"
  TARGET_VAR: "Weather Type"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          environment-file: MLProject/conda.yaml
          activate-environment: ml-env
          python-version: "3.12.7"

      - name: Install extra pip packages
        shell: bash -l {0}
        run: |
          pip install mlflow

      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          mlflow run ./MLProject --env-manager=conda 

      - name: Get latest MLflow run_id from model folder
        shell: bash -l {0}
        run: |
          RUN_ID=$(find mlruns/0 -type d -path "*/artifacts/model" | sort | tail -n1 | cut -d'/' -f3)
          if [ -z "$RUN_ID" ]; then
            echo "No MLflow model artifact found."
            exit 1
          fi
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id from model artifact: $RUN_ID"


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        shell: bash -l {0}
        run: |
          echo "Checking model URI..."
          echo "Using run ID: $RUN_ID"
          ls -l "mlruns/0/$RUN_ID/artifacts/model"
          mlflow models build-docker --model-uri "mlruns:/0/$RUN_ID/model" --name weather-model

      - name: Tag Docker Image
        run: docker tag weather-model ${{ secrets.DOCKER_HUB_USERNAME }}/weather-model:latest

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/weather-model:latest
